### ISSUE TITLE
DefaultSpringNavigationElementInfoProvider

### ISSUE THREAD

**Issue by mirkoliver** [appreciated/vaadin-app-layout#108]
In the DemoUI is used a DefaultSpringNavigationElementInfoProvider - this is not any more existing in the addon.

**Comment by mirkoliver** [comment]
Additionally: AppBarDesign is now AppLayoutDesign

**Comment by appreciated** [comment]
Thats correct thank you for the info! I will fix it right away.

**Comment by appreciated** [comment]
So I fixed the code examples in this repository and updated the code examples in the Vaadin Directory. If I still missed something just let me know!

**Comment by mirkoliver** [comment]
Danke nach Darmstadt for your quick answer - but I still see DefaultSpringNavigationElementInfoProvider both in the example in Vaadin Directory as well as on github:  [https://github.com/appreciated/vaadin-app-layout/commit/facb4a6f4db004d2953d7c2f9c177d9cbb9ebf49](https://github.com/appreciated/vaadin-app-layout/commit/facb4a6f4db004d2953d7c2f9c177d9cbb9ebf49). Or do I understand something wrong?

**Comment by mirkoliver** [comment]
Danke nach Darmstadt ;) for the quick answer and fix!!! By the way: really great AddOn!

**Comment by appreciated** [comment]
Thank you :smile: you are welcome! 

> but I still see DefaultSpringNavigationElementInfoProvider both in the example in Vaadin Directory as well as on github: facb4a6. Or do I understand something wrong?
This mostly due to a bug of the Vaadin directory (it sometimes doesn't update the views).
Also I seem to have forgotten :roll_eyes: to rename the related builder method. Will fix it right away.

**Comment by appreciated** [comment]
Hmm I should catch these kind of exception more informative. It seems like one of your Views you added to the AppLayout does not have a "@NavigatorViewName" Annotation. 

This seems to cause this issue.

**Comment by mirkoliver** [comment]
Yes! Right!! I've also just found this out by debugging. I've now added @NavigatorViewName everywhere and it works. Perhaps it would be good to give a hint in the Vaadin Directory example.

**Comment by mirkoliver** [comment]
Great! Thank you!!!
